import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Layout guest",
  description: "Generated by create next app",
};

export default function GuestLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <>
      {children}
    </>
  );
}
