import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import ThemeRegistry from "@/theme-registry/theme.registry";
import AppHeader from "@/components/header/app.header";
import AppFooter from "@/components/footer/app.footer";
import { getServerSession } from "next-auth";
import { authOptions } from "../api/auth/[...nextauth]/route";
import { redirect } from "next/navigation";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session: any = await getServerSession(authOptions);
  if (session.user.role_id == "admin") {
    redirect("/admin")
  }

  return (
    <>
      <AppHeader />
      {children}
      <AppFooter />
    </>
  );
}
